spring:
  application:
    name: Event-Driven-Architecture-KAFKA
  cloud:
    stream:
      bindings:
        pageEventConsumer-in-0:
          destination: R1
        pageEventSupplier-out-0:
          destination: R2
        pageEventFunction-in-0:
          destination: R1
        pageEventFunction-out-0:
          destination: R3
        kStreamKStreamFunction-in-0:
          destination: R2
        kStreamKStreamFunction-out-0:
          destination: R4
      kafka:
        binder:
          configuration:
            commit:
              interval:
                ms: 1000
    function:
      definition: pageEventConsumer; pageEventSupplier
  integration:
    poller:
      fixed-delay: 100
